# Generated by Django 4.2.13 on 2026-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_1_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2_sent",
            field=models.BooleanField(default=False),
        ),
    ]
