# Generated by Django 4.2.13 on 2026-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctoravailability_doctorbreak"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={"ordering": ["date"]},
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together={("doctor", "date")},
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="day",
        ),
    ]
